### ISSUE TITLE
Handle sensor data to perform single and long-press clicks

### ISSUE THREAD

**Issue by lusimoncelli** [lusimoncelli/barco-aac#15]
- Define how we're going to handle the sensor data to perform single and long-press clicks in different activities.

**Comment by milalangone** [comment]
Useful links:
- https://www.sitepoint.com/using-android-sensors-application/
- https://stackoverflow.com/questions/49833489/how-to-send-constantly-changing-sensor-data-using-bluetooth
- https://chat.openai.com/share/ff22cc7b-6ae6-4b8b-87aa-5259da5633d8

**Comment by lusimoncelli** [comment]
Steps:

- [x] Press button in BluetoothActivity
- [x] Add thread for better performance
- [x] Handle single click in a different screen
- [x] Handle long click in a different screen
- [x] Replicate on every other screen
