### ISSUE TITLE
Bug: text input not working properly when clicking button

### ISSUE THREAD

**Issue by lusimoncelli** [lusimoncelli/barco-aac#2]

**Comment by milalangone** [comment]
El chat me tiró está datita pero no me quiero entrometer en tus issues:

package com.example.barcoapp;

import android.os.Bundle;
import android.os.Handler;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

public class AlphanumericKeyboardActivity extends AppCompatActivity {

    private TextView enteredText;
    private Button[] letterButtons;
    private int currentButtonIndex = 0;
    private Handler handler = new Handler();
    private boolean loopRunning = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.alphanumeric_layout);

        enteredText = findViewById(R.id.enteredText);

        letterButtons = new Button[]{
                findViewById(R.id.button_A),
                findViewById(R.id.button_B),
                // Add the rest of your buttons here
        };

        for (Button button : letterButtons) {
            button.setVisibility(View.INVISIBLE);
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    String buttonText = ((Button) view).getText().toString();
                    enteredText.append(buttonText);
                }
            });
        }

        startButtonLoop();
    }

    private void setButtonVisibility(int index, int visibility) {
        if (index >= 0 && index < letterButtons.length) {
            letterButtons[index].setVisibility(visibility);
        }
    }

    private void startButtonLoop() {
        loopRunning = true;
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                setButtonVisibility(currentButtonIndex, View.INVISIBLE);
                currentButtonIndex = (currentButtonIndex + 1) % letterButtons.length;
                setButtonVisibility(currentButtonIndex, View.VISIBLE);

                if (loopRunning) {
                    handler.postDelayed(this, 1000);
                }
            }
        }, 1000);
    }

    private void stopButtonLoop() {
        loopRunning = false;
        currentButtonIndex = 0;
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        stopButtonLoop();
    }
}
