### ISSUE TITLE
Create new keyboard screen

### ISSUE THREAD

**Issue by milalangone** [lusimoncelli/barco-aac#7]

**Comment by milalangone** [comment]
only access to photos of the device

**Comment by lusimoncelli** [comment]
added grid to show selected photos

**Comment by milalangone** [comment]
Me parece que es mejor no hacer lo de las fotos y solo configurar botones con texto. 

Se me ocurre que de manera predeterminada haya 4 botones y solo puedas configurarles el texto, es decir, la creación de los botones no forma parte de la creación del nuevo teclado, solo se les modifica el texto.
